# Generated by Django 3.2.25 on 2025-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
